### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by chpecson** [tinovyatkin/is-localhost-ip#167]
Is any @types definition for this awesome library?

Hit a roadblock while trying it out on typescript:
```
This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.ts
```

Thank you.

**Comment by tinovyatkin** [comment]
@chpecson I'm rewriting it into TypeScript, so, this should be solved

**Comment by chpecson** [comment]
Awesome. Thanks!

Do you have a timeline for typescript support?

**Comment by chpecson** [comment]
Gonna close this issue since this will be re written to typescript. Thanks.
