### ISSUE TITLE
dns cache

### ISSUE THREAD

**Issue by azu** [tinovyatkin/is-localhost-ip#8]
> Though the call to dns.lookup() will be asynchronous from JavaScript's perspective, it is implemented as a synchronous call to getaddrinfo(3) that runs on libuv's threadpool. This can have surprising negative performance implications for some applications, see the UV_THREADPOOL_SIZE documentation for more information.
> -- [DNS | Node.js v12.9.0 Documentation](https://nodejs.org/api/dns.html#dns_implementation_considerations)

Maybe, dns `lookup` have negative performance implications.
I think that lookup should be cached.

However, dns `lookup` has not `ttl` option.

- [Native DNS caching for lookups · Issue #5893 · nodejs/node](https://github.com/nodejs/node/issues/5893)

## Related

- [yahoo/dnscache: dnscache for Node](https://github.com/yahoo/dnscache)
- [LCMApps/dns-lookup-cache: An implementation to speed up the nodejs "dns.lookup" method by avoiding thread pool and using DNS TTL cache for particular hostname](https://github.com/LCMApps/dns-lookup-cache)

**Comment by tinovyatkin** [comment]
Do you expect a lot of the equal queries? I think in this case the better solutions will be a LRU cache around, but not sure if it should be part of this library of wrap around. What do you think? Cache all requests with LRU cache?

**Comment by azu** [comment]
> I think in this case the better solutions will be a LRU cache around, but not sure if it should be part of this library of wrap around.

Agree.

I'm ok that caching is out of scope of this library.

📝 I've filed this issue by following reason.
`isLocalhost` look like primitive function.
So, It is difficult that the library user care about the performance.

**Comment by tinovyatkin** [comment]
That's exactly the reason why I don't want to make it another `lodash` or `request` and keep the core thing simple. Depending on a use case you may or may not want to cache the result.

**Comment by tinovyatkin** [comment]
Digging deeper, we definitely can't replace `lookup` with `resolve` here, because it will loose `hosts` lookup and that is the most common use case for this library.
